[tools]
bun = '1.3.1'
act = '0.2.82'


[tasks.act]
description = "run github action in act"
run = "act pull_request --container-architecture linux/amd64 -e fixtures/github-pr-event.json"

[tasks.local-preview]
description = "run local preview of sentinel with DEBUG level logs"
run = "bun preview"
dir = "./packages/sentinel"
env = {SENTINEL_LOG_LEVEL = 'debug'} 
